### ISSUE TITLE
ChickpeaMine tissue expression--no definitions for tissue abbreviations

### ISSUE THREAD

**Issue by amcooksey** [LegumeFederation/Interface-and-Usability#12]

**Comment by sammyjava** [comment]
This has just been implemented on the gene report page expression bar chart in dev: SoyMine and I'm finishing up BeanMine. Probably promote both to production today. If you're talking about the gene list heat map, that's different. There are two different places where expression is shown: bar chart on the gene report page (was a heat map bar on previous versions like ChickpeaMine) and a heat map on a gene list analysis page.

**Comment by sammyjava** [comment]
Closing this since it is now implemented in the code which will be rolled out mine by mine, SoyMine is currently the latest greatest.
