### ISSUE TITLE
(www.)legumefederation.org SSL cert needs to be renewed

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/Interface-and-Usability#15]
Hello,

Your certificate (or certificates) for the names listed below will expire in
19 days (on 23 Dec 17 04:00 +0000). Please make sure to renew
your certificate before then, or visitors to your website will encounter errors.

legumefederation.org
www.legumefederation.org

For any questions or support, please visit https://community.letsencrypt.org/.
Unfortunately, we can't provide support by email.

**Comment by jd-campbell** [comment]
Forward to Nathan Weeks.


=========================
Jacqueline D. Campbell (Farrell), PhD
Iowa State University
jdjax@iastate.edu<mailto:jdjax@iastate.edu>
##Sent from my iPhone
##Please excuse any spelling or grammar errors.
_____________________________

**Comment by nathanweeks** [comment]
Updated cron job on new host to ```certbot renew``` nightly. Note that historically we have received these emails sometimes days after the certificate was renewed; the certificate expiration date can be verified e.g. with Chrome using Developer Tools > Security > View Certificate
