### ISSUE TITLE
PeanutMine tissue expression--hard to tell whether there isn't any or you're just missing it

### ISSUE THREAD

**Issue by amcooksey** [LegumeFederation/Interface-and-Usability#9]
In PeanutMine when you look at the gene information page it is hard to tell whether there is no known tissue expression OR if there is tissue expression but you can't find it. The small type that indicates there are no expression data is easily missed--it looks like a section divider.

**Comment by sammyjava** [comment]
Informative message added when there is no expression data. Quick turnaround, huh?!!
